version: "3.8"
services:
    app:
        build:
            args:
                user: ${USER}
                uid: 1000
            context: .
        image: ${PHP_APP_IMAGE_NAME}
        container_name: ${APP_CONTAINER_NAME}
        restart: always
        working_dir: ${CONTAINER_WORKING_DIR}
        expose:
            - "8000"
        volumes:
            - .:${CONTAINER_WORKING_DIR}
        environment:
            APP_NAME: ${APP_NAME}
            APP_ENV: ${APP_ENV}
            APP_KEY: ${APP_KEY}
            APP_DEBUG: ${APP_DEBUG}
            APP_URL: ${APP_URL}
            APP_TIMEZONE: ${APP_TIMEZONE}
            JWT_EXP: ${JWT_EXP}
            DEFAULT_DB_CONNECTION: ${DEFAULT_DB_CONNECTION}
            DB_CONNECTION: ${DB_CONNECTION}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_NAME}
            DB_USERNAME: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            CACHE_DRIVER: ${CACHE_DRIVER}
            QUEUE_CONNECTION: ${QUEUE_CONNECTION}
    db:
        image: mysql:5.7.32
        container_name: ${DATABASE_CONTAINER_NAME}
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - "db_data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        ports:
            - "${PMA_WEB_PORT}:80"
        restart: always
        environment:
            PMA_ARBITRARY: 1

volumes:
    db_data:
