version: "3.8"
services:
    front_app:
        build: .
        container_name: ${APP_CONTAINER_NAME}
        ports:
            - 80:3000
        command: "tail -f /dev/null"
        volumes:
            - .:/usr/src
            - /usr/src/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
